const express = require('express');
const router = express.Router();

// ── Portfolio Data - Mahboob Raza ──────────────────────────────────
const portfolioData = {
  name: "Mahboob Raza",
  title: "Aspiring Full Stack Web Developer",
  tagline: "B.Tech CSE (May 2026) | MERN Stack | 300+ DSA Problems Solved 🚀",
  about: "I am a passionate Full Stack Developer (B.Tech CSE, May 2026) with hands-on experience in building responsive web applications using modern technologies.I specialize in creating responsive web applications and have practical experience with HTML, CSS, JavaScript, React, Node.js, Express.js, and PHP. I have implemented REST APIs, databases, and user authentication in real-world projects. Additionally, I have solved over 300 DSA problems in Java, which reflects my strong problem-solving skills and coding proficiency.",

  stats: [
    { number: "4+", label: "Real Projects" },
    { number: "300+", label: "DSA Problems Solved" },
    { number: "8.3", label: "CGPA" },
    { number: "2+", label: "Internships" }
  ],

  skills: [
    { name: "HTML / CSS", level: 92, icon: "🌐" },
    { name: "JavaScript", level: 85, icon: "⚡" },
    { name: "React.js", level: 80, icon: "⚛️" },
    { name: "Node.js", level: 80, icon: "🟢" },
    { name: "Express.js", level: 80, icon: "🚂" },
    { name: "MongoDB", level: 72, icon: "🍃" },
    { name: "MySQL", level: 85, icon: "💾" },
    { name: "Java (DSA)", level: 75, icon: "☕" },
    { name: "Bootstrap", level: 85, icon: "🎨" },
    { name: "REST APIs", level: 80, icon: "🔗" },
    { name: "PHP", level: 60, icon: "🐘" },
  ],
  dsaProblems: {
  easy: {
    count: 175,
    percent: 85,
    questions: [
      { name: "1. Two Sum", link: "https://leetcode.com/problems/two-sum/" },
      { name: "9. Palindrome Number", link: "https://leetcode.com/problems/palindrome-number/" },
      { name: "13. Roman to Integer", link: "https://leetcode.com/problems/roman-to-integer/" },
      { name: "14. Longest Common Prefix", link: "https://leetcode.com/problems/longest-common-prefix/" },
      { name: "20. Valid Parentheses", link: "https://leetcode.com/problems/valid-parentheses/" },
      { name: "21. Merge Two Sorted Lists", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { name: "26. Remove Duplicates from Sorted Array", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
      { name: "27. Remove Element", link: "https://leetcode.com/problems/remove-element/" },
      { name: "28. Find the Index of the First Occurrence in a String", link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/" },
      { name: "35. Search Insert Position", link: "https://leetcode.com/problems/search-insert-position/" },
      { name: "58. Length of Last Word", link: "https://leetcode.com/problems/length-of-last-word/" },
      { name: "66. Plus One", link: "https://leetcode.com/problems/plus-one/" },
      { name: "67. Add Binary", link: "https://leetcode.com/problems/add-binary/" },
      { name: "70. Climbing Stairs", link: "https://leetcode.com/problems/climbing-stairs/" },
      { name: "83. Remove Duplicates from Sorted List", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/" },
      { name: "84. Largest Rectangle in Histogram", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
      { name: "88. Merge Sorted Array", link: "https://leetcode.com/problems/merge-sorted-array/" },
      { name: "94. Binary Tree Inorder Traversal", link: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "100. Same Tree", link: "https://leetcode.com/problems/same-tree/" },
      { name: "101. Symmetric Tree", link: "https://leetcode.com/problems/symmetric-tree/" },
      { name: "104. Maximum Depth of Binary Tree", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
      { name: "110. Balanced Binary Tree", link: "https://leetcode.com/problems/balanced-binary-tree/" },
      { name: "111. Minimum Depth of Binary Tree", link: "https://leetcode.com/problems/minimum-depth-of-binary-tree/" },
      { name: "112. Path Sum", link: "https://leetcode.com/problems/path-sum/" },
      { name: "118. Pascal's Triangle", link: "https://leetcode.com/problems/pascals-triangle/" },
      { name: "119. Pascal's Triangle II", link: "https://leetcode.com/problems/pascals-triangle-ii/" },
      { name: "121. Best Time to Buy and Sell Stock", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { name: "125. Valid Palindrome", link: "https://leetcode.com/problems/valid-palindrome/" },
      { name: "136. Single Number", link: "https://leetcode.com/problems/single-number/" },
      { name: "141. Linked List Cycle", link: "https://leetcode.com/problems/linked-list-cycle/" },
      { name: "144. Binary Tree Preorder Traversal", link: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "145. Binary Tree Postorder Traversal", link: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
      { name: "160. Intersection of Two Linked Lists", link:" https://leetcode.com/problems/intersection-of-two-linked-lists/description/" },
      { name: "168. Excel Sheet Column Title", link: "https://leetcode.com/problems/excel-sheet-column-title/" },
      { name: "169. Majority Element", link: "https://leetcode.com/problems/majority-element/" },
      { name: "171. Excel Sheet Column Number", link: "https://leetcode.com/problems/excel-sheet-column-number/" },
      { name: "175. Combine Two Tables", link: "https://leetcode.com/problems/combine-two-tables/" },
      { name: "181. Employees Earning More Than Their Managers", link: "https://leetcode.com/problems/employees-earning-more-than-their-managers/" },
      { name: "182. Duplicate Emails", link: "https://leetcode.com/problems/duplicate-emails/" },
      { name: "183. Customers Who Never Order", link: "https://leetcode.com/problems/customers-who-never-order/" },
      { name: "190. Reverse Bits", link: "https://leetcode.com/problems/reverse-bits/" },
      { name: "191. Number of 1 Bits", link: "https://leetcode.com/problems/number-of-1-bits/" },
      { name: "196. Delete Duplicate Emails", link: "https://leetcode.com/problems/delete-duplicate-emails/" },
      { name: "197. Rising Temperature", link: "https://leetcode.com/problems/rising-temperature/" },
      { name: "202. Happy Number", link: "https://leetcode.com/problems/happy-number/" },
      { name: "203. Remove Linked List Elements", link: "https://leetcode.com/problems/remove-linked-list-elements/" },
      { name: "206. Reverse Linked List", link: "https://leetcode.com/problems/reverse-linked-list/" },
      { name: "217. Contains Duplicate", link: "https://leetcode.com/problems/contains-duplicate/" },
      { name: "219. Contains Duplicate II", link: "https://leetcode.com/problems/contains-duplicate-ii/" },
      { name: "225. Implement Stack using Queues", link: "https://leetcode.com/problems/implement-stack-using-queues/" },
      { name: "226. Invert Binary Tree", link: "https://leetcode.com/problems/invert-binary-tree/" },
      { name: "231. Power of Two", link: "https://leetcode.com/problems/power-of-two/" },
      { name: "232. Implement Queue using Stacks", link: "https://leetcode.com/problems/implement-queue-using-stacks/" },
      { name: "234. Palindrome Linked List", link: "https://leetcode.com/problems/palindrome-linked-list/" },
      { name: "242. Valid Anagram", link: "https://leetcode.com/problems/valid-anagram/" },
      { name: "257. Binary Tree Paths", link: "https://leetcode.com/problems/binary-tree-paths/" },
      { name: "258. Add Digits", link: "https://leetcode.com/problems/add-digits/" },
      { name: "263. Ugly Number", link: "https://leetcode.com/problems/ugly-number/" },
      { name: "268. Missing Number", link: "https://leetcode.com/problems/missing-number/" },
      { name: "283. Move Zeroes", link: "https://leetcode.com/problems/move-zeroes/" },
      { name: "290. Word Pattern", link: "https://leetcode.com/problems/word-pattern/" },
      { name: "326. Power of Three", link: "https://leetcode.com/problems/power-of-three/" },
      { name: "338. Counting Bits", link: "https://leetcode.com/problems/counting-bits/" },
      { name: "342. Power of Four", link: "https://leetcode.com/problems/power-of-four/" },
      { name: "344. Reverse String", link: "https://leetcode.com/problems/reverse-string/" },
      { name: "345. Reverse Vowels of a String", link: "https://leetcode.com/problems/reverse-vowels-of-a-string/" },
      { name: "349. Intersection of Two Arrays", link: "https://leetcode.com/problems/intersection-of-two-arrays/" },
      { name: "350. Intersection of Two Arrays II", link: "https://leetcode.com/problems/intersection-of-two-arrays-ii/" },
      { name: "367. Valid Perfect Square", link: "https://leetcode.com/problems/valid-perfect-square/" },
      { name: "383. Ransom Note", link: "https://leetcode.com/problems/ransom-note/" },
      { name: "387. First Unique Character in a String", link: "https://leetcode.com/problems/first-unique-character-in-a-string/" },
      { name: "389. Find the Difference", link: "https://leetcode.com/problems/find-the-difference/" },
       { name: "392. Is Subsequence", link: "https://leetcode.com/problems/is-subsequence/description/" },
      { name: "404. Sum of Left Leaves", link: "https://leetcode.com/problems/sum-of-left-leaves/" },
      { name: "412. Fizz Buzz", link: "https://leetcode.com/problems/fizz-buzz/" },
      { name: "414. Third Maximum Number", link: "https://leetcode.com/problems/third-maximum-number/" },
      { name: "448. Find All Numbers Disappeared in an Array", link: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/" },
      { name: "455. Assign Cookies", link: "https://leetcode.com/problems/assign-cookies/" },
      { name: "485. Max Consecutive Ones", link: "https://leetcode.com/problems/max-consecutive-ones/" },
      { name: "496. Next Greater Element I", link: "https://leetcode.com/problems/next-greater-element-i/" },
      { name: "500. Keyboard Row", link: "https://leetcode.com/problems/keyboard-row/" },
      { name: "501. Find Mode in Binary Search Tree", link: "https://leetcode.com/problems/find-mode-in-binary-search-tree/" },
      { name: "506. Relative Ranks", link: "https://leetcode.com/problems/relative-ranks/" },
      { name: "509. Fibonacci Number", link: "https://leetcode.com/problems/fibonacci-number/" },
      { name: "511. Game Play Analysis I", link: "https://leetcode.com/problems/game-play-analysis-i/" },
      { name: "520. Detect Capital", link: "https://leetcode.com/problems/detect-capital/" },
      { name: "530. Minimum Absolute Difference in BST", link: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/" },
      { name: "543. Diameter of Binary Tree", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { name: "557. Reverse Words in a String III", link: "https://leetcode.com/problems/reverse-words-in-a-string-iii/" },
       { name: "561. Array Partition", link: "https://leetcode.com/problems/array-partition/description/" },
      { name: "572. Subtree of Another Tree", link: "https://leetcode.com/problems/subtree-of-another-tree/" },
      { name: "575. Distribute Candies", link: "https://leetcode.com/problems/distribute-candies/" },
      { name: "577. Employee Bonus", link: "https://leetcode.com/problems/employee-bonus/" },
      { name: "584. Find Customer Referee", link: "https://leetcode.com/problems/find-customer-referee/" },
      { name: "586. Customer Placing the Largest Number of Orders", link: "https://leetcode.com/problems/customer-placing-the-largest-number-of-orders/" },
      { name: "594. Longest Harmonious Subsequence", link: "https://leetcode.com/problems/longest-harmonious-subsequence/" },
      { name: "595. Big Countries", link: "https://leetcode.com/problems/big-countries/" },
      { name: "596. Classes More Than 5 Students", link: "https://leetcode.com/problems/classes-more-than-5-students/" },
      { name: "599. Minimum Index Sum of Two Lists", link: "https://leetcode.com/problems/minimum-index-sum-of-two-lists/" },
      { name: "610. Triangle Judgement", link: "https://leetcode.com/problems/triangle-judgement/" },
      { name: "617. Merge Two Binary Trees", link: "https://leetcode.com/problems/merge-two-binary-trees/" },
      { name: "619. Biggest Single Number", link: "https://leetcode.com/problems/biggest-single-number/" },
      { name: "620. Not Boring Movies", link: "https://leetcode.com/problems/not-boring-movies/" },
      { name: "627. Swap Salary", link: "https://leetcode.com/problems/swap-salary/" },
      { name: "628. Maximum Product of Three Numbers", link: "https://leetcode.com/problems/maximum-product-of-three-numbers/" },
      { name: "637. Average of Levels in Binary Tree", link: "https://leetcode.com/problems/average-of-levels-in-binary-tree/" },
      { name: "643. Maximum Average Subarray I", link: "https://leetcode.com/problems/maximum-average-subarray-i/" },
      { name: "645. Set Mismatch", link: "https://leetcode.com/problems/set-mismatch/" },
      { name: "653. Two Sum IV - Input is a BST", link: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/" },
      { name: "657. Robot Return to Origin", link: "https://leetcode.com/problems/robot-return-to-origin/" },
      { name: "674. Longest Continuous Increasing Subsequence", link: "https://leetcode.com/problems/longest-continuous-increasing-subsequence/" },
      { name: "682. Baseball Game", link: "https://leetcode.com/problems/baseball-game/" },
      { name: "705. Design HashSet", link: "https://leetcode.com/problems/design-hashset/" },
      { name: "709. To Lower Case", link: "https://leetcode.com/problems/to-lower-case/" },
      { name: "771. Jewels and Stones", link: "https://leetcode.com/problems/jewels-and-stones/" },
      { name: "783. Minimum Distance Between BST Nodes", link: "https://leetcode.com/problems/minimum-distance-between-bst-nodes/" },
      { name: "804. Unique Morse Code Words", link: "https://leetcode.com/problems/unique-morse-code-words/" },
      { name: "812. Largest Triangle Area", link: "https://leetcode.com/problems/largest-triangle-area/" },
      { name: "821. Shortest Distance to a Character", link: "https://leetcode.com/problems/shortest-distance-to-a-character/" },
      { name: "824. Goat Latin", link: "https://leetcode.com/problems/goat-latin/" },
      { name: "832. Flipping an Image", link: "https://leetcode.com/problems/flipping-an-image/" },
      { name: "867. Transpose Matrix", link: "https://leetcode.com/problems/transpose-matrix/" },
      { name: "876. Middle of the Linked List", link: "https://leetcode.com/problems/middle-of-the-linked-list/" },
      { name: "884. Uncommon Words from Two Sentences", link: "https://leetcode.com/problems/uncommon-words-from-two-sentences/" },
      { name: "888. Fair Candy Swap", link: "https://leetcode.com/problems/fair-candy-swap/description/" },
      { name: "905. Sort Array By Parity", link: "https://leetcode.com/problems/sort-array-by-parity/" },
      { name: "922. Sort Array By Parity II", link: "https://leetcode.com/problems/sort-array-by-parity-ii/" },
      { name: "938. Range Sum of BST", link: "https://leetcode.com/problems/range-sum-of-bst/" },
      { name: "961. N-Repeated Element in Size 2N Array", link: "https://leetcode.com/problems/n-repeated-element-in-size-2n-array/" },
      { name: "976. Largest Perimeter Triangle", link: "https://leetcode.com/problems/largest-perimeter-triangle/" },
      { name: "977. Squares of a Sorted Array", link: "https://leetcode.com/problems/squares-of-a-sorted-array/" },
      { name: "1021. Remove Outermost Parentheses", link: "https://leetcode.com/problems/remove-outermost-parentheses/" },
      { name: "1050. Actors and Directors Who Cooperated At Least Three Times", link: "https://leetcode.com/problems/actors-and-directors-who-cooperated-at-least-three-times/" },
      { name: "1051. Height Checker", link: "https://leetcode.com/problems/height-checker/" },
      { name: "1068. Product Sales Analysis I", link: "https://leetcode.com/problems/product-sales-analysis-i/" },
      { name: "1075. Project Employees I", link: "https://leetcode.com/problems/project-employees-i/" },
      { name: "1108. Defanging an IP Address", link: "https://leetcode.com/problems/defanging-an-ip-address/" },
      { name: "1122. Relative Sort Array", link: "https://leetcode.com/problems/relative-sort-array/" },
      { name: "1128. Number of Equivalent Domino Pairs", link: "https://leetcode.com/problems/number-of-equivalent-domino-pairs/" },
      { name: "1141. User Activity for the Past 30 Days I", link: "https://leetcode.com/problems/user-activity-for-the-past-30-days-i/" },
      { name: "1148. Article Views I", link: "https://leetcode.com/problems/article-views-i/" },
      { name: "1179. Reformat Department Table", link: "https://leetcode.com/problems/reformat-department-table/" },
      { name: "1189. Maximum Number of Balloons", link: "https://leetcode.com/problems/maximum-number-of-balloons/" },
      { name: "1211. Queries Quality and Percentage", link: "https://leetcode.com/problems/queries-quality-and-percentage/" },
      { name: "1221. Split a String in Balanced Strings", link: "https://leetcode.com/problems/split-a-string-in-balanced-strings/" },
      { name: "1251. Average Selling Price", link: "https://leetcode.com/problems/average-selling-price/" },
      { name: "1280. Students and Examinations", link: "https://leetcode.com/problems/students-and-examinations/" },
      { name: "1281. Subtract the Product and Sum of Digits of an Integer", link: "https://leetcode.com/problems/subtract-the-product-and-sum-of-digits-of-an-integer/" },
      { name: "1290. Convert Binary Number in a Linked List to Integer", link: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/" },
      { name: "1295. Find Numbers with Even Number of Digits", link: "https://leetcode.com/problems/find-numbers-with-even-number-of-digits/" },
      { name: "1299. Replace Elements with Greatest Element on Right Side", link: "https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/" },
      { name: "1309. Decrypt String from Alphabet to Integer Mapping", link: "https://leetcode.com/problems/decrypt-string-from-alphabet-to-integer-mapping/" },
      { name: "1313. Decompress Run-Length Encoded List", link: "https://leetcode.com/problems/decompress-run-length-encoded-list/" },
      { name: "1342. Number of Steps to Reduce a Number to Zero", link: "https://leetcode.com/problems/number-of-steps-to-reduce-a-number-to-zero/" },
      { name: "1346. Check If N and Its Double Exist", link: "https://leetcode.com/problems/check-if-n-and-its-double-exist/" },
      { name: "1365. How Many Numbers Are Smaller Than the Current Number", link: "https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/" },
      { name: "1370. Increasing Decreasing String", link: "https://leetcode.com/problems/increasing-decreasing-string/" },
      { name: "1374. Generate a String With Characters That Have Odd Counts", link: "https://leetcode.com/problems/generate-a-string-with-characters-that-have-odd-counts/" },
      { name: "1378. Replace Employee ID With The Unique Identifier", link: "https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/" },
      { name: "1389. Create Target Array in the Given Order", link: "https://leetcode.com/problems/create-target-array-in-the-given-order/" },
      { name: "1408. String Matching in an Array", link: "https://leetcode.com/problems/string-matching-in-an-array/" },
      { name: "1431. Kids With the Greatest Number of Candies", link: "https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/" },
      { name: "1436. Destination City", link: "https://leetcode.com/problems/destination-city/description/" },
      { name: "1470. Shuffle the Array", link: "https://leetcode.com/problems/shuffle-the-array/" },
      { name: "1475. Final Prices With a Special Discount in a Shop", link: "https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop/" },
      { name: "1480. Running Sum of 1d Array", link: "https://leetcode.com/problems/running-sum-of-1d-array/" },
      { name: "1484. Group Sold Products By The Date", link: "https://leetcode.com/problems/group-sold-products-by-the-date/" },
      { name: "1512. Number of Good Pairs", link: "https://leetcode.com/problems/number-of-good-pairs/" },
      { name: "1528. Shuffle String", link: "https://leetcode.com/problems/shuffle-string/" },
      { name: "1581. Problem of the Pots", link: "https://leetcode.com/problems/problem-of-the-pots/" },
      { name: "1582. Special Positions in a Binary Matrix", link: "https://leetcode.com/problems/special-positions-in-a-binary-matrix/" },
      { name: "1587. Bank Account Summary II", link: "https://leetcode.com/problems/bank-account-summary-ii/" },
      { name: "1633. Percentage of Users Attended a Contest", link: "https://leetcode.com/problems/percentage-of-users-attended-a-contest/" },
      { name: "1661. Average Time of Process per Machine", link: "https://leetcode.com/problems/average-time-of-process-per-machine/" },
      { name: "1662. Check If Two String Arrays are Equivalent", link: "https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/" },
      { name: "1668. Maximum Repeating Substring", link: "https://leetcode.com/problems/maximum-repeating-substring/" },
      { name: "1672. Richest Customer Wealth", link: "https://leetcode.com/problems/richest-customer-wealth/" },
      { name: "1678. Goal Parser Interpretation", link: "https://leetcode.com/problems/goal-parser-interpretation/" },
      { name: "1683. Invalid Tweets", link: "https://leetcode.com/problems/invalid-tweets/" },
      { name: "1704. Determine if String Halves Are Alike", link: "https://leetcode.com/problems/determine-if-string-halves-are-alike/" },
      { name: "1710. Maximum Units on a Truck", link: "https://leetcode.com/problems/maximum-units-on-a-truck/" },
      { name: "1729. Find Followers Count", link: "https://leetcode.com/problems/find-followers-count/" },
      { name: "1731. The Number of Employees Which Report to Each Employee", link: "https://leetcode.com/problems/the-number-of-employees-which-report-to-each-employee/" },
      { name: "1732. Find the Highest Altitude", link: "https://leetcode.com/problems/find-the-highest-altitude/" },
      { name: "1757. Recyclable and Low Fat Products", link: "https://leetcode.com/problems/recyclable-and-low-fat-products/" },
      { name: "1758. Minimum Changes To Make Alternating Binary String", link: "https://leetcode.com/problems/minimum-changes-to-make-alternating-binary-string/" },
      { name: "1768. Merge Strings Alternately", link: "https://leetcode.com/problems/merge-strings-alternately/" },
      { name: "1789. Primary Department for Each Employee", link: "https://leetcode.com/problems/primary-department-for-each-employee/" },
      { name: "1795. Rearrange Products Table", link: "https://leetcode.com/problems/rearrange-products-table/" },
      { name: "1832. Check if the Sentence Is Pangram", link: "https://leetcode.com/problems/check-if-the-sentence-is-pangram/" },
      { name: "1844. Replace All Digits with Characters", link: "https://leetcode.com/problems/replace-all-digits-with-characters/" },
      { name: "1859. Sorting the Sentence", link: "https://leetcode.com/problems/sorting-the-sentence/" },
      { name: "1873. Calculate Special Bonus", link: "https://leetcode.com/problems/calculate-special-bonus/" },
      { name: "1886. Determine Whether Matrix Can Be Obtained By Rotation", link: "https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/" },
      { name: "1913. Maximum Product Difference Between Two Pairs", link: "https://leetcode.com/problems/maximum-product-difference-between-two-pairs/" },
      { name: "1920. Build Array from Permutation", link: "https://leetcode.com/problems/build-array-from-permutation/" },
      { name: "1929. Concatenation of Array", link: "https://leetcode.com/problems/concatenation-of-array/" },
      { name: "1941. Check if All Characters Have Equal Number of Occurrences", link: "https://leetcode.com/problems/check-if-all-characters-have-equal-number-of-occurrences/" },
      { name: "1965. Employees With Missing Information", link: "https://leetcode.com/problems/employees-with-missing-information/" },
      { name: "1978. Employees Whose Manager Left the Company", link: "https://leetcode.com/problems/employees-whose-manager-left-the-company/" },
       { name: "1984. Minimum Difference Between Highest and Lowest of K Scores", link: "https://leetcode.com/problems/minimum-difference-between-highest-and-lowest-of-k-scores/description/" },
      { name: "2000. Reverse Prefix of Word", link: "https://leetcode.com/problems/reverse-prefix-of-word/" },
      { name: "2011. Final Value of Variable After Performing Operations", link: "https://leetcode.com/problems/final-value-of-variable-after-performing-operations/" },
      { name: "2022. Convert 1D Array Into 2D Array", link: "https://leetcode.com/problems/convert-1d-array-into-2d-array/" },
      { name: "2089. Find Target Indices After Sorting Array", link: "https://leetcode.com/problems/find-target-indices-after-sorting-array/" },
      { name: "2094. Finding 3-Digit Even Numbers", link: "https://leetcode.com/problems/finding-3-digit-even-numbers/" },
      { name: "2114. Maximum Number of Words Found in Sentences", link: "https://leetcode.com/problems/maximum-number-of-words-found-in-sentences/" },
      { name: "2138. Divide a String Into Groups of Size k", link: "https://leetcode.com/problems/divide-a-string-into-groups-of-size-k/" },
      { name: "2235. Add Two Integers", link: "https://leetcode.com/problems/add-two-integers/" },
      { name: "2236. Root Equals Sum of Children", link: "https://leetcode.com/problems/root-equals-sum-of-children/" },
      { name: "2293. Min Max Game", link: "https://leetcode.com/problems/min-max-game/" },
      { name: "2356. Number of Unique Subjects Taught by Each Teacher", link: "https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher/" },
      { name: "2413. Smallest Even Multiple", link: "https://leetcode.com/problems/smallest-even-multiple/" },
      { name: "2460. Apply Operations to an Array", link: "https://leetcode.com/problems/apply-operations-to-an-array/" },
      { name: "2529. Maximum Count of Positive Integer and Negative Integer", link: "https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer/" },
      { name: "2570. Merge Two 2D Arrays by Summing Values", link: "https://leetcode.com/problems/merge-two-2d-arrays-by-summing-values/" },
      { name: "2643. Row With Maximum Ones", link: "https://leetcode.com/problems/row-with-maximum-ones/" },
      { name: "2733. Neither Minimum nor Maximum", link: "https://leetcode.com/problems/neither-minimum-nor-maximum/" },
      { name: "2859. Sum of Values at Indices With K Set Bits", link: "https://leetcode.com/problems/sum-of-values-at-indices-with-k-set-bits/" },
      { name: "2864. Maximum Odd Binary Number", link: "https://leetcode.com/problems/maximum-odd-binary-number/" },
      { name: "2932. Maximum Strong Pair XOR I", link: "https://leetcode.com/problems/maximum-strong-pair-xor-i/" },
      { name: "2965. Find Missing and Repeated Values", link: "https://leetcode.com/problems/find-missing-and-repeated-values/" },
      { name: "3005. Count Elements With Maximum Frequency", link: "https://leetcode.com/problems/count-elements-with-maximum-frequency/" },
      { name: "3158. Find the XOR of Numbers Which Appear Twice", link: "https://leetcode.com/problems/find-the-xor-of-numbers-which-appear-twice/" },
      { name: "3423. Maximum Difference Between Adjacent Elements in a Circular Array", link: "https://leetcode.com/problems/maximum-difference-between-adjacent-elements-in-a-circular-array/" },
      { name: "3436. Find Valid Emails", link: "https://leetcode.com/problems/find-valid-emails/" },
      { name: "3536.  Maximum Product of Two Digits", link: "https://leetcode.com/problems/maximum-product-of-two-digits/description/" },
       { name: "3633. Earliest Finish Time for Land and Water Rides I", link: "https://leetcode.com/problems/earliest-finish-time-for-land-and-water-rides-i/description/" },
      { name: "3684. Maximum Sum of Subsequence With Non-adjacent Elements", link: "https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements/" },
    ]
  },
  medium: {
    count: 66,
    percent: 60,
    questions: [
      { name: "3. Longest Substring Without Repeating Characters", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { name: "7. Reverse Integer", link: "https://leetcode.com/problems/reverse-integer/" },
      { name: "11. Container With Most Water", link: "https://leetcode.com/problems/container-with-most-water/" },
      { name: "12. Integer to Roman", link: "https://leetcode.com/problems/integer-to-roman/" },
      { name: "15. 3Sum", link: "https://leetcode.com/problems/3sum/" },
      { name: "16. 3Sum Closest", link: "https://leetcode.com/problems/3sum-closest/" },
      { name: "18. 4Sum", link: "https://leetcode.com/problems/4sum/" },
       { name: "19.  Remove Nth Node From End of List", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/description/" },
        { name: "24.  Swap Nodes in Pairs", link: "https://leetcode.com/problems/swap-nodes-in-pairs/description/" },
      { name: "33. Search in Rotated Sorted Array", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { name: "34. Find First and Last Position of Element in Sorted Array", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
      { name: "43. Multiply Strings", link: "https://leetcode.com/problems/multiply-strings/" },
      { name: "48. Rotate Image", link: "https://leetcode.com/problems/rotate-image/" },
      { name: "50. Pow(x, n)", link: "https://leetcode.com/problems/powx-n/" },
      { name: "53. Maximum Subarray", link: "https://leetcode.com/problems/maximum-subarray/" },
      { name: "54. Spiral Matrix", link: "https://leetcode.com/problems/spiral-matrix/" },
      { name: "59. Spiral Matrix II", link: "https://leetcode.com/problems/spiral-matrix-ii/" },
      { name: "74. Search a 2D Matrix", link: "https://leetcode.com/problems/search-a-2d-matrix/" },
      { name: "75. Sort Colors", link: "https://leetcode.com/problems/sort-colors/" },
      { name: "80. Remove Duplicates from Sorted Array II", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/" },
      { name: "82. Remove Duplicates from Sorted List II", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/" },
      { name: "102. Binary Tree Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { name: "107. Binary Tree Level Order Traversal II", link: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/" },
      { name: "113. Path Sum II", link: "https://leetcode.com/problems/path-sum-ii/" },
      { name: "137. Single Number II", link: "https://leetcode.com/problems/single-number-ii/" },
      { name: "142. Linked List Cycle II", link: "https://leetcode.com/problems/linked-list-cycle-ii/" },
      { name: "151. Reverse Words in a String", link: "https://leetcode.com/problems/reverse-words-in-a-string/" },
      { name: "176. Second Highest Salary", link: "https://leetcode.com/problems/second-highest-salary/" },
      { name: "178. Rank Scores", link: "https://leetcode.com/problems/rank-scores/" },
      { name: "180. Consecutive Numbers", link: "https://leetcode.com/problems/consecutive-numbers/" },
      { name: "184. Department Highest Salary", link: "https://leetcode.com/problems/department-highest-salary/" },
      { name: "204. Count Primes", link: "https://leetcode.com/problems/count-primes/" },
      { name: "222. Count Complete Tree Nodes", link: "https://leetcode.com/problems/count-complete-tree-nodes/" },
      { name: "229. Majority Element II", link: "https://leetcode.com/problems/majority-element-ii/" },
      { name: "230. Kth Smallest Element in a BST", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { name: "237. Delete Node in a Linked List", link: "https://leetcode.com/problems/delete-node-in-a-linked-list/" },
      { name: "240. Search a 2D Matrix II", link: "https://leetcode.com/problems/search-a-2d-matrix-ii/" },
      { name: "260. Single Number III", link: "https://leetcode.com/problems/single-number-iii/" },
      { name: "287. Find the Duplicate Number", link: "https://leetcode.com/problems/find-the-duplicate-number/" },
      { name: "328. Odd Even Linked List", link: "https://leetcode.com/problems/odd-even-linked-list/" },
      { name: "442. Find All Duplicates in an Array", link: "https://leetcode.com/problems/find-all-duplicates-in-an-array/" },
      { name: "451. Sort Characters By Frequency", link: "https://leetcode.com/problems/sort-characters-by-frequency/" },
      { name: "503. Next Greater Element II", link: "https://leetcode.com/problems/next-greater-element-ii/" },
      { name: "513. Find Bottom Left Tree Value", link: "https://leetcode.com/problems/find-bottom-left-tree-value/" },
      { name: "540. Single Element in a Sorted Array", link: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
      { name: "560. Subarray Sum Equals K", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
      { name: "606. Construct String from Binary Tree", link: "https://leetcode.com/problems/construct-string-from-binary-tree/" },
      { name: "626. Exchange Seats", link: "https://leetcode.com/problems/exchange-seats/" },
      { name: "678. Valid Parenthesis String", link: "https://leetcode.com/problems/valid-parenthesis-string/" },
      { name: "692. Top K Frequent Words", link: "https://leetcode.com/problems/top-k-frequent-words/" },
       { name: "792. Number of Matching Subsequences", link: "https://leetcode.com/problems/number-of-matching-subsequences/description/" },
      { name: "848. Shifting Letters", link: "https://leetcode.com/problems/shifting-letters/" },
      { name: "849. Maximize Distance to Closest Person", link: "https://leetcode.com/problems/maximize-distance-to-closest-person/" },
      { name: "852. Peak Index in a Mountain Array", link: "https://leetcode.com/problems/peak-index-in-a-mountain-array/" },
      { name: "865. Smallest Subtree with all the Deepest Nodes", link: "https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes/" },
      { name: "1204. Last Person to Fit in the Bus", link: "https://leetcode.com/problems/last-person-to-fit-in-the-bus/" },
      { name: "1393. Capital Gain/Loss", link: "https://leetcode.com/problems/capital-gainloss/" },
      { name: "1669. Merge In Between Linked Lists", link: "https://leetcode.com/problems/merge-in-between-linked-lists/" },
      { name: "1934. Confirmation Rate", link: "https://leetcode.com/problems/confirmation-rate/" },
      { name: "2095. Delete the Middle Node of a Linked List", link: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/" },
      { name: "2221. Find Triangular Sum of an Array", link: "https://leetcode.com/problems/find-triangular-sum-of-an-array/" },
      { name: "2433. Find The Original Array of Prefix Xor", link: "https://leetcode.com/problems/find-the-original-array-of-prefix-xor/" },
      { name: "3475. DNA Pattern Recognition", link: "https://leetcode.com/problems/dna-pattern-recognition/" },
      { name: "3847. Smallest Number With All Positive Bits Set", link: "https://leetcode.com/problems/smallest-number-with-all-positive-bits-set/" },
      { name: "3848. Word Frequencies", link: "https://leetcode.com/problems/word-frequencies/" },
      { name: "3849. Maximum Destroyed Robots", link: "https://leetcode.com/problems/maximum-destroyed-robots/" },
    ]
  },
  hard: {
    count: 5,
    percent: 30,
    questions: [
      { name: "4. Median of Two Sorted Arrays", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { name: "23. Merge k Sorted Lists", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
      { name: "42. Trapping Rain Water", link: "https://leetcode.com/problems/trapping-rain-water/" },
      { name: "84. Largest Rectangle in Histogram", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
      { name: "2156. Find Substring With Given Hash Value", link: "https://leetcode.com/problems/find-substring-with-given-hash-value/" },
    ]
  }
},

  projects: [
    {
      title: "Wanderlust – Booking Web App",
      desc: "Full-stack accommodation booking platform with user authentication, CRUD listings, image uploads, reviews, and payment integration for better booking experience.",
      tech: ["Node.js", "Express.js", "EJS", "MongoDB"],
      github: "https://github.com/Mahboobraza01/wanderlust",
      live: "https://wanderlust-2i83.onrender.com/listings",
      emoji: "🏕️"
    },
    {
      title: "PG Life – PG Accommodation Website",
      desc: "A Responsive PG accommodation website with city-wise search and filtering. The frontend is built using React, and the backend is developed with PHP + MySQL, connected via REST APIs.",
      tech: ["React", "PHP", "MySQL", "Bootstrap"],
      github: "https://github.com/Mahboobraza01/PG-life",
      live: "https://mahboob-portfolio.infinityfreeapp.com/pglife/index.php",
      emoji: "🏠"
    },
    {
      title: "Real-time Weather Telegram Bot",
      desc: "A real-time weather bot built with Node.js that integrates the Telegram API and OpenWeatherMap API. It provides the live weather of any city instantly.",
      tech: ["Node.js", "Telegram API", "OpenWeatherMap API"],
      github: "https://github.com/Mahboobraza01/weathet-bot",
      live: "https://web.telegram.org/k/#@WeatherBabaBot",
      emoji: "🌤️"
    },
    {
      title: "Portfolio Website",
      desc: "A portfolio website built using Node.js, Express.js, and EJS featuring a dark theme and a fully responsive design.",
      tech: ["Node.js", "Express.js", "EJS", "CSS"],
      github: "https://github.com/Mahboobraza01/myPortfolio",
      live: "https://my-portfolio-tltd.onrender.com/",
      emoji: "🎨"
    },
    {
     title: "Tic-Tac-Toe",
      desc: "Built a responsive Tic Tac Toe game with two play modes (human vs human, human vs computer) featuring win/draw detection, score tracking, and dynamic UI updates using vanilla JavaScript DOM manipulation.",
      tech: ["JavaScript", "HTML", "CSS"],
      github: "https://github.com/Mahboobraza01/TIC-TAC-TOE",
      live: "https://mahboobraza01.github.io/TIC-TAC-TOE/",
      emoji: "🎮" 
    }
  ],

  experience: [
    {
      role: "Full Stack Website Design & Development (Online)",
      company: "Internship Studio (Remote)",
      duration: "Jan 2026 – March 2026",
      points: [
        "Completed online training in HTML, CSS, JavaScript, Bootstrap",
        "Developed and Design responsive e-commerce website as Capstone Assignment",
        "Practice and Learn the workflow of Real-world Project"
      ]
    },
    {
      role: "Web Development with AI (Online)",
      company: "Internshala Training (Remote)",
      duration: "Oct 2024 – Dec 2024",
      points: [
        "Gained Hand-on experience in HTML, CSS, JavaScript, PHP and REact.",
        "Developed a responsive PG (paying guest) accommodation platform with city-wise search and dynamic filtering, improving property discoverability for users across multiple cities",
        "Integrated AI tools into the web development workflow, accelerating debugging, code review, and feature delivery",
        "Certificate: Web Development with AI – Internshala (Sep 2025)"
      ]
    },
    {
      role: "B.Tech – Computer Science & Engineering",
      company: "Gurukula Kangri (Deemed to be University), Haridwar",
      duration: "Nov 2022 – May 2026",
      points: [
        "CGPA: 8.2 — consistent academic performance",
        "Core subjects: Data Structures, Algorithms, DBMS, OS, Web Technologies",
        "300+ DSA problems solved on LeetCode using Java"
      ]
    }
  ],

  certifications: [
    { name: "Web Development with AI", issuer: "Internshala", date: "Sep 2025" }
  ],

  social: {
    github: "https://github.com/Mahboobraza01",
    linkedin: "https://www.linkedin.com/in/mahboobraza/",
    twitter: "https://twitter.com",
    youtube: "https://youtube.com",
    instagram: "https://instagram.com"
  },

  email: "mahboobraza.muz@gmail.com",
  phone: "+91 6200548714",
  location: "Haridwar, Uttarakhand"
};

// ── Routes ─────────────────────────────────────────────────────────
router.get('/', (req, res) => {
  res.render('index', { data: portfolioData, page: 'home' });
});

router.get('/about', (req, res) => {
  res.render('about', { data: portfolioData, page: 'about' });
});

router.get('/projects', (req, res) => {
  res.render('projects', { data: portfolioData, page: 'projects' });
});

router.get('/experience', (req, res) => {
  res.render('experience', { data: portfolioData, page: 'experience' });
});

module.exports = router;
module.exports.portfolioData = portfolioData;
